// console.log(a + b);
// console.log("This line is never reached")

// throw new ReferenceError();

try {
    Number(5).toPrecision(300)
    } catch(e) {
    console.log("There was an error")
    }